#!/usr/bin/python

import lxml
from lxml import etree
import time
import sys, os
import argparse
import tntapi

namespaces={"nc":"urn:ietf:params:xml:ns:netconf:base:1.0",
	"nd":"urn:ietf:params:xml:ns:yang:ietf-network",
	"netconf-node":"urn:tntapi:netconf-node"}

def main():

	of = open(sys.argv[2], "w")
	tree=etree.parse(sys.argv[1])

	networks = tree.xpath('/nc:config/nd:networks',namespaces=namespaces)[0]
	network = networks.xpath('nd:network',namespaces=namespaces)[0]
	conns = tntapi.network_connect(network)

	assert(conns != None)

	filter="""<filter type="xpath" select="/"/>"""
	network_w_state_data = tntapi.network_get_state(network, conns, filter=filter)
	network_w_all_data = tntapi.network_get_config(network_w_state_data, conns, filter=filter)
	networks.replace(network,network_w_all_data)
	of.write(lxml.etree.tostring(tree))
	of.close()
	return 0

sys.exit(main())

