#!/usr/bin/python

import lxml
from lxml import etree
import time
import sys, os
import argparse
import tntapi

namespaces={"nc":"urn:ietf:params:xml:ns:netconf:base:1.0",
	"nd":"urn:ietf:params:xml:ns:yang:ietf-network",
	"netconf-node":"urn:tntapi:netconf-node"}


def main():

	tree=etree.parse(sys.argv[1])
	orig_tree=tree

	network = tree.xpath('/nc:config/nd:networks/nd:network', namespaces=namespaces)[0]
	conns = tntapi.network_connect(network)

	assert(conns != None)

	for conn_id in conns:
		print conn_id

		inst_id="/nc:config/nd:networks/nd:network/nd:node[nd:node-id='%s']/netconf-node:config"%(conn_id)
		print inst_id
		config = orig_tree.xpath(inst_id,namespaces=namespaces)[0]
		print lxml.etree.tostring(config)
		tntapi.copy_config(conns[conn_id],lxml.etree.tostring(config))


	tntapi.network_commit(conns)
	return 0

sys.exit(main())

